version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:      
      - dados:/var/lib/postgresql/data
      - ./sql:/scripts
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql