version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
      PGDATA: /tmp                 
    volumes:      
      - dados:/var/lib/postgresql/data
      - ./sql:/scripts
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh   
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:      
      - REDIS_HOST=queue
      - DB_HOST=db
      - DB_NAME=envios
      - DB_USER=postgres
      - DB_PASSWORD=123456
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
    



    
    
